# -*- coding: utf-8 -*-
"""
AI Text Detection module.
Calculates stylometric features (sentence uniformity, formality, punctuation distribution, connector density, vocabulary richness)
to estimate the probability that the text was generated by an AI assistant.
"""

import re
import math
from collections import Counter
from typing import Dict, List, Union
from analyzers.stats import split_into_sentences

def calculate_sentence_uniformity(sentences: List[str]) -> float:
    """
    Measures the standard deviation of sentence lengths to evaluate structural uniformity.
    
    Args:
        sentences (List[str]): List of sentences.
        
    Returns:
        float: Score between 0.0 and 1.0 (higher means highly uniform/monotonous sentence lengths, typical for AI).
    """
    if len(sentences) < 2:
        return 0.5

    lengths = [len(s.split()) for s in sentences]
    avg_len = sum(lengths) / len(lengths)
    if avg_len == 0:
        return 0.5

    variance = sum((l - avg_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    cv = std_dev / avg_len

    if cv < 0.15:
        return 0.9
    elif cv < 0.3:
        return 0.7
    elif cv < 0.5:
        return 0.5
    elif cv < 0.8:
        return 0.3
    else:
        return 0.15

def calculate_vocabulary_richness(text: str) -> float:
    """
    Evaluates Type-Token Ratio (TTR) to assess lexical diversity.
    
    Args:
        text (str): The input text.
        
    Returns:
        float: Diversity score between 0.0 and 1.0.
    """
    words = re.findall(r'\b\w+\b', text.lower())
    if len(words) < 5:
        return 0.5

    ttr = len(set(words)) / len(words)

    if ttr > 0.75:
        return 0.7
    elif ttr > 0.6:
        return 0.55
    elif ttr > 0.45:
        return 0.4
    else:
        return 0.3

def calculate_formality_score(text: str) -> float:
    """
    Measures ratio of formal connectors vs informal markers to determine style level.
    
    Args:
        text (str): The input text.
        
    Returns:
        float: Formality rating between 0.0 and 1.0.
    """
    text_lower = text.lower()

    informal_markers = [
        r'\b(lol|haha|хаха|ахах|омг|wtf|btw|imho|кста|чел|норм|ок|окей|tbh|ngl|fr|imo|smh|idk)\b',
        r'\.{3,}',
        r'!{2,}',
        r'\?{2,}',
    ]

    informal_count = 0
    for pattern in informal_markers:
        informal_count += len(re.findall(pattern, text_lower))

    formal_markers = [
        r'\b(furthermore|moreover|additionally|consequently|nevertheless|however|therefore|thus|hence|accordingly)\b',
        r'\b(крім того|більш того|отже|таким чином|відповідно|зокрема|водночас|безперечно)\b',
        r'\b(it is important to note|it should be noted|it is worth mentioning)\b',
        r'\b(варто зазначити|слід зауважити|необхідно підкреслити)\b',
        r'\b(in conclusion|to summarize|in summary|overall)\b',
    ]

    formal_count = 0
    for pattern in formal_markers:
        formal_count += len(re.findall(pattern, text_lower))

    words_count = max(len(text.split()), 1)
    informal_ratio = informal_count / words_count
    formal_ratio = formal_count / words_count

    if formal_ratio > 0.03:
        score = 0.85
    elif formal_ratio > 0.015:
        score = 0.7
    elif formal_ratio > 0.005:
        score = 0.6
    elif informal_ratio > 0.05:
        score = 0.15
    elif informal_ratio > 0.02:
        score = 0.25
    else:
        score = 0.45

    return score

def calculate_repetition_patterns(text: str) -> float:
    """
    Inspects starting words and averages length consistency to find recurring patterns.
    
    Args:
        text (str): The input text.
        
    Returns:
        float: Repetitive behavior rating.
    """
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) < 3:
        return 0.5

    starts = [s.split()[0].lower() if s.split() else '' for s in sentences]
    start_counter = Counter(starts)
    most_common = start_counter.most_common(1)[0][1] if start_counter else 0
    start_rep = most_common / len(sentences)

    words = re.findall(r'\b\w+\b', text)
    avg_word_len = sum(len(w) for w in words) / max(len(words), 1)

    score = 0.5
    if avg_word_len > 6:
        score += 0.15
    if start_rep > 0.4:
        score += 0.1

    return min(score, 1.0)

def calculate_punctuation_score(text: str) -> float:
    """
    Analyzes punctuation density and structure.
    
    Args:
        text (str): The input text.
        
    Returns:
        float: Punctuation score.
    """
    if len(text) < 20:
        return 0.5

    commas = text.count(',')
    periods = text.count('.')
    excl = text.count('!')
    quest = text.count('?')
    semi = text.count(';')
    colons = text.count(':')

    total_punct = commas + periods + excl + quest + semi + colons
    words_count = max(len(text.split()), 1)
    punct_ratio = total_punct / words_count

    if 0.12 < punct_ratio < 0.28:
        score = 0.65
    else:
        score = 0.35

    if semi > 0 or colons > 1:
        score += 0.1
    if excl > 2:
        score -= 0.15

    return max(0, min(score, 1.0))

def calculate_connector_density(text: str) -> float:
    """
    Calculates density of formal connecting clauses per sentence.
    
    Args:
        text (str): The input text.
        
    Returns:
        float: Connector density score.
    """
    text_lower = text.lower()
    connectors = [
        r'\b(however|moreover|furthermore|additionally|consequently|therefore|nevertheless)\b',
        r'\b(in addition|as a result|on the other hand|for instance|for example|in contrast)\b',
        r'\b(significantly|particularly|specifically|essentially|fundamentally)\b',
        r'\b(kрім того|більш того|зокрема|таким чином|відповідно|натомість|водночас)\b',
    ]

    connector_count = 0
    for pattern in connectors:
        connector_count += len(re.findall(pattern, text_lower))

    sentences = split_into_sentences(text)
    if not sentences:
        return 0.5

    density = connector_count / len(sentences)

    if density > 0.5:
        return 0.9
    elif density > 0.3:
        return 0.7
    elif density > 0.15:
        return 0.55
    else:
        return 0.3

def detect_ai_text(text: str) -> Dict[str, Union[float, str, Dict[str, float], bool]]:
    """
    Processes all metrics to evaluate overall AI generation probability.
    
    Args:
        text (str): The input text to inspect.
        
    Returns:
        Dict[str, Union[float, str, Dict[str, float], bool]]: AI assessment, breakdown scores, and error status.
    """
    if len(text.strip()) < 30:
        return {
            'ai_probability': 0.0,
            'human_probability': 100.0,
            'verdict': 'Tekst jest zbyt krótki do analizy',
            'verdict_level': 'uncertain',
            'details': {},
            'error': True
        }

    sentences = split_into_sentences(text)

    uniformity = calculate_sentence_uniformity(sentences)
    vocabulary = calculate_vocabulary_richness(text)
    formality = calculate_formality_score(text)
    repetition = calculate_repetition_patterns(text)
    punctuation = calculate_punctuation_score(text)
    connectors = calculate_connector_density(text)

    weights = {
        'uniformity': 0.20,
        'vocabulary': 0.12,
        'formality': 0.28,
        'repetition': 0.12,
        'punctuation': 0.12,
        'connectors': 0.16
    }

    ai_score = (
        uniformity * weights['uniformity'] +
        vocabulary * weights['vocabulary'] +
        formality * weights['formality'] +
        repetition * weights['repetition'] +
        punctuation * weights['punctuation'] +
        connectors * weights['connectors']
    )

    ai_probability = round(ai_score * 100, 1)
    ai_probability = max(5.0, min(95.0, ai_probability))

    if ai_probability >= 75:
        verdict = "Bardzo prawdopodobne, że napisane przez AI"
        verdict_level = "high"
    elif ai_probability >= 55:
        verdict = "Możliwe, że napisane przez AI"
        verdict_level = "medium"
    elif ai_probability >= 40:
        verdict = "Nieokreślone"
        verdict_level = "uncertain"
    elif ai_probability >= 25:
        verdict = "Raczej napisane przez człowieka"
        verdict_level = "low"
    else:
        verdict = "Prawdopodobnie napisane przez człowieka"
        verdict_level = "very_low"

    return {
        'ai_probability': ai_probability,
        'human_probability': round(100 - ai_probability, 1),
        'verdict': verdict,
        'verdict_level': verdict_level,
        'details': {
            'Jednorodność zdań': round(uniformity * 100, 1),
            'Bogactwo leksykalne': round(vocabulary * 100, 1),
            'Formalność stylu': round(formality * 100, 1),
            'Wzorce powtórzeń': round(repetition * 100, 1),
            'Interpunkcja': round(punctuation * 100, 1),
            'Gęstość konektorów': round(connectors * 100, 1)
        },
        'error': False
    }
